# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name : Setup the node env
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name : Install the dependencies
        run : npm install --force
        
#       - name : Change the selenoid port
#         run : docker system prune --volumes
        
        
#       - name : build webdriverio-test docker image
#         run : make build-clean

      - name : Run wdio test scripts
        env:
           USEREMAIL: ${{secrets.USEREMAIL}}
           USERPASSWORD: ${{secrets.USERPASSWORD}}
        run : npx wdio

#       - name: Get allure history
#         uses: actions/checkout@v2
#         if: always()
#         continue-on-error: true
#         with:
#           ref: gh-pages
#           path: gh-pages

#       - name: Setup allure report
#         uses: simple-elf/allure-report-action@master
#         if: always()
#         id: allure-report
#         with:
#           allure_results: allure-results
#           allure_history: allure-history
#           keep_reports: 20

#       - name: Deploy report to Github Pages
#         if: always()
#         uses: peaceiris/actions-gh-pages@v2
#         env:
#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PUBLISH_BRANCH: gh-pages
#           PUBLISH_DIR: allure-history
